#include <p18cxxx.h>

#include <delays.h>

#include "util.h"

#include "a2d.h"

extern A2D_Timeout, Timeout_Counter;

void Init_ADC() 
{
	
  A2D_Module_Disable;
  ANCON1 = 0xFF; // ALL INPUTS ARE ANALOG
  ANCON2 = 0xFF; // ALL INPUTS ARE ANALOG
  ANCON3 = 0xFF; // ALL INPUTS ARE ANALOG
  ADCON1H = 0x04; // 12 BITS MODE, DECIMAL UNSIGNED 
  ADCON1L = 0x00; // MANUAL SAMPLING MODE 
  ADCON2H = 0x48; // POSITIVE VOLTAGE REFFERENCE IS VREF+, EACH CHANNEL HAS OWN BUFFER, DON'T SCAN INPUTS
  ADCON2L = 0x00; // TRIGGER INTERRUPT EACH SAMPLE
  ADCON3H = 0x0A; // A2D USES SYSTEM CLOCK, SAMPLE TIME IS 10 TAD
  ADCON3L = 0x02; // A2D CONVERSION CLOCK 3 X TOSC
  ADCON5H = 0x00; // AUTO SCAN IS DISABLED
  ADCON5L = 0x00; // CONVERSION DATA IS SAVED TO THE BUFFER
  ADCSS0H = 0x00; 
  ADCSS0L = 0x00; 
  ADCSS1H = 0x00; 
  ADCSS1L = 0x00; 
  ADCHS0H = 0x00; // SAMPLE B CONFIGURED TO CHANNEL 0, NOT RELEVANT IN SCAN MODE
  ADCHS0L = 0x00; // SAMPLE A CONFIGURED TO CHANNEL 0, NOT RELEVANT IN SCAN MODE
  ADCHIT1H = 0x00;
  ADCHIT1L = 0x00;
  ADCHIT0H = 0x00;
  ADCHIT0L = 0x00;

}

void Wait_For_Completion(void)
{
	while (!A2D_Conversion_Completed);
}

void A2D_Manual_Convert(char A2D_Channel_Number) // EXECUTE ONE CONVERSION IN MANUAL WORKING MODE
{
	switch (A2D_Channel_Number) // OPEN THE RELEVANT ADC INPUT
		{
			case AMP_FRWD_PWR_SNS2: 
				ADCHS0H = 0x00; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x00; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case AMP_FRWD_PWR_SNS1: 
				ADCHS0H = 0x01; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x01; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case AMP_RVRS_PWR_SNS2: 
				ADCHS0H = 0x02; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x02; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case PHN_ADC_SPR: 
				ADCHS0H = 0x04; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x04; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case VAC_PRESR_SENS: 
				ADCHS0H = 0x05; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x05; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case HP_TEC_Power_SNS: 
				ADCHS0H = 0x06; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x06; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case AMP_TEMP_SNS: 
				ADCHS0H = 0x07; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x07; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case N5V: 
				ADCHS0H = 0x08; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x08; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case DDS1_BEFORE_SW_SNS: 
				ADCHS0H = 0x09; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x09; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case DDS2_BEFORE_SW_SNS: 
				ADCHS0H = 0x0A; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x0A; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case SMA1_OUT_SNS: 
				ADCHS0H = 0x0B; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x0B; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case SMA2_OUT_SNS: 
				ADCHS0H = 0x0C; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x0C; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case AMP_RVRS_PWR_SNS1: 
				ADCHS0H = 0x0D; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x0D; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case AMP_CUR_SNS2: 
				ADCHS0H = 0x0E; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x0E; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case AMP_CUR_SNS1: 
				ADCHS0H = 0x0F; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x0F; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case P3_3V: 
				ADCHS0H = 0x10; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x10; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case P5V: 
				ADCHS0H = 0x11; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x11; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case P12V: 
				ADCHS0H = 0x12; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x12; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case GEN_ADC1: 
				ADCHS0H = 0x13; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x13; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case N12V: 
				ADCHS0H = 0x14; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x14; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case P24V: 
				ADCHS0H = 0x15; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x15; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case P150V: 
				ADCHS0H = 0x16; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x16; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			case P48V: 
				ADCHS0H = 0x17; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x17; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
			default:
				ADCHS0H = 0x00; // SAMPLE B CONFIGURED TO RELEVANT CHANNEL NUMBER 
				ADCHS0L = 0x00; // SAMPLE A CONFIGURED TO RELEVANT CHANNEL NUMBER 
				break;
		}
	A2D_Sample_Start;
	PIC_PC_ACK = 1;
	Delay_6_25US(3); // 19USEC
	PIC_PC_ACK = 0;
	A2D_Convertion_Start;
}

int A2D_Value_Read(char A2D_Channel_Number) // EXECUTE ONE CONVERSION IN MANUAL WORKING MODE
{
	switch (A2D_Channel_Number) // OPEN THE RELEVANT ADC INPUT
		{
			case AMP_FRWD_PWR_SNS2: 
				return (ADCBUF0);
				break;
			case AMP_FRWD_PWR_SNS1: 
				return (ADCBUF1);
				break;
			case AMP_RVRS_PWR_SNS2: 
				return (ADCBUF2);
				break;
			case PHN_ADC_SPR: 
				return (ADCBUF4);
				break;
			case VAC_PRESR_SENS: 
				return (ADCBUF5);
				break;
			case HP_TEC_Power_SNS: 
				return (ADCBUF6);
				break;
			case AMP_TEMP_SNS: 
				return (ADCBUF7);
				break;
			case N5V: 
				return (ADCBUF8);
				break;
			case DDS1_BEFORE_SW_SNS: 
				return (ADCBUF9);
				break;
			case DDS2_BEFORE_SW_SNS: 
				return (ADCBUF10);
				break;
			case SMA1_OUT_SNS: 
				return (ADCBUF11);
				break;
			case SMA2_OUT_SNS: 
				return (ADCBUF12); 
				break;
			case AMP_RVRS_PWR_SNS1: 
				return (ADCBUF13);
				break;
			case AMP_CUR_SNS2: 
				return (ADCBUF14);
				break;
			case AMP_CUR_SNS1: 
				return (ADCBUF15);
				break;
			case P3_3V: 
				return (ADCBUF16); 
				break;
			case P5V: 
				return (ADCBUF17);
				break;
			case P12V: 
				return (ADCBUF18);
				break;
			case GEN_ADC1: 
				return (ADCBUF19);
				break;
			case N12V: 
				return (ADCBUF20);
				break;
			case P24V: 
				return (ADCBUF21);
				break;
			case P150V: 
				return (ADCBUF22);
				break;
			case P48V: 
				return (ADCBUF23);
				break;
			default:
				return (0);
				break;
		}
}
